Спецоперация по девладленизации и детипизации вк-ио
negezor/vk-io pull request #480
Opened 2022-03-31 22:25 UTC by realicedicerice

В связи с последними событиями я принял решение о проведении спецоперации по девладленизации и детипизации кодбазы Я принимаю это решение не только из соображений проектной, а чтобы обеспечить безопасность всем остальным объектам инфраструктуры нпм Таким образом, ответственность за выявление и пресечение девидакты ложится не только на меня, но и на высших должностных лиц контрибуторов репы, вместе с коими и происходит решение о проведении операции. Разграничительная линия на нашем обычном уровне допуска к информации не нарушена.

2022-03-31 23:57 UTC, Nekonyx commented
![image](https://user-images.githubusercontent.com/16444061/161168776-9842eae2-eb2b-4115-b175-bf4aa5fd1754.png)

~40 тыс. изменений и 0 breaking changes.
Я бы мержнул.

2022-04-01 15:28 UTC, flameflick approved these changes
Seems perfect!

2022-04-17 05:28 UTC, MrZillaGold requested changes
Найс рофлы у вас конечно 🙄

2022-04-17 05:31 UTC, MrZillaGold commented
У вас тесты не проходят, поправьте перед мержом, пожалуйста 🙃

2022-04-17 05:43 UTC, merged

2022-04-17 05:46 UTC, negezor commented
✊ ✊ ✊